### PR TITLE
Big refactor, pulls out bloat, adds web-installer web-config

### PR DESCRIPTION
**Pull request by arcbtc**

### CODE REVIEW

**Comment by BenGWeeks** [comment]
On opening fossa.ino I still see:

image

I then removed the `\Arduino\libraries\` folder of libraries previously imported, and copied the libraries back in.

Successfully compiled and uploaded.

However, does not detect coins (the coins are register and going into the machine) or allow notes to be sent through. Presumably .available() is false as the devices unsuccessfully enabled.

```
Windows 11
IDE 2.3.2 & IDE IDE 1.8.19
ESP32 Dev Module
```

Can you please confirm these settings (standard for ESP32 Dev Module) are correct:

image

Also set the serial monitor to 115200 baud but not seeing serial messages for some reason now.

I do miss the funky UI ;-)

**Comment by arcbtc** [comment]
Try arduino 2, that's what I compiled on. On the coin mech they register for me, prob wiring issue.

**Comment by arcbtc** [comment]
I can add back the funky homescreen?

**Comment by BenGWeeks** [comment]
No rush. I was thinking of spending some time on the UX/UI anyway. I do like the approach of separating the functionality into separate uno files now.

Tomorrow I'll rule out the board and connect in directly. I think having the same connector types as the bill and coin acceptors on the LNBits board would also ensure cables are connected the right way round (I'm assuming they are as they power on).

**Pull request merged**
